POST http://localhost:3000/dispositivos
Content-Type: application/json

 {
    "dispositivodata": "29/07/25", 
    "dispositivohora": "15:49",
    "dispositivoambiente": 26
 }


###

GET http://localhost:3000/dispositivos/ambiente/26

###

GET http://localhost:3000/dispositivos

###

GET http://localhost:3000/dispositivos/50

###

PUT http://localhost:3000/dispositivos/49
Content-Type: application/json

{
  "dispositivotemp": 35,
  "dispositivodata": "29/07/25",
  "dispositivohora": "15:51",
  "dispositivoambiente":26
}

### 

DELETE  http://localhost:3000/dispositivos/49

###

GET http://localhost:3000/notificacao/dispositivo/49

###

GET http://localhost:3000/notificacao/3

###

GET http://localhost:3000/notificacao

###

DELETE  http://localhost:3000/notificacao/3